package com.nitiaayog.apnesaathi.database.constants

object Columns {
    const val Id: String = "id"
    const val CallId: String = "call_id"
    const val VolunteerId: String = "volunteer_id"
    const val GrievanceId: String = "grievance_id"
    const val EmailId: String = "email_id"
    const val Name: String = "name"
    const val ContactNumber: String = "contact_number"
    const val Age: String = "age"
    const val Gender: String = "gender"
    const val Ratings: String = "rating"
    const val Address: String = "address"
    const val State: String = "state"
    const val District: String = "district"
    const val Block: String = "block"
    const val CallStatus: String = "call_status"
    const val GrievanceStatus: String = "grievance_status"
    const val CallSubStatus: String = "call_sub_status"
    const val TalkedWith: String = "talked_with"
    const val Remark: String = "remark"
    const val LoggedDateTime: String = "logged_date_time"
    const val IsDiabetic: String = "is_diabetic"
    const val IsBloodPressure: String = "is_blood_pressure"
    const val IsLungAilment: String = "is_lung_ailment"
    const val IsCancerOrMajorSurgery: String = "cancer_or_major_surgery"
    const val OtherAilments: String = "other_ailments"
    const val RemarkOnMedicalHistory: String = "remarks_on_medical_history"
    const val InfoTalkAbout: String = "info_talked_about"

    const val IsSrCitizenAwareOfCovid19: String = "is_sr_citizen_aware_of_covid_19"
    const val IsSymptomsPreventionDiscussed: String = "is_symptoms_prevention_discussed"
    const val WhichPracticeNotFollowed: String = "practice_not_followed"

    const val NoticedBehaviouralChanges: String = "behavioural_change_noticed"
    const val HasCovidSymptoms: String = "has_covid_symptoms"
    const val HasCough: String = "has_cough"
    const val HasFever: String = "has_fever"
    const val HasShortnessOfBreath: String = "has_shortness_of_breath"
    const val HasSoreThroat: String = "has_sore_throat"
    const val QuarantineStatus: String = "quarantine_status"
    const val LackOfEssentialServices: String = "lack_of_essential_services"
    const val FoodShortage: String = "food_shortage"
    const val MedicineShortage: String = "medicine_shortage"
    const val AccessToBankingIssue: String = "access_to_banking_issue"
    const val UtilitySupplyIssue: String = "utility_supply_issue"
    const val HygieneIssue: String = "hygiene_issue"
    const val SafetyIssue: String = "safety_issue"
    const val Description: String = "description"
    const val EmergencyServiceIssue: String = "emergency_service_issue"
    const val PhoneAndInternetIssue: String = "phone_and_internet_issue"
    const val IsEmergencyServiceRequired: String = "is_emergency_service_required"
    const val RemarksImportantInfo: String = "important_remark"
    const val DeleteIDAfterSync: String = "delete_after_sync"
    const val CreatedDate: String = "created_date"
    const val GrievanceType: String = "grievance_type"
    const val Priority: String = "priority"
    const val LastUpdateOn: String = "last_update_on"
    const val UnderReviewDate: String = "under_review_date"
    const val ResolvedDate: String = "resolved_date"
    const val ReviewRemarks: String = "review_remarks"
    const val ResolvedRemarks: String = "resolved_remarks"
    const val IsSynced: String = "is_synced"

    const val FirstName: String = "first_name"
    const val LastName: String = "last_name"
    const val ProfilePic: String = "profile_pic"
    const val Role: String = "role"
    const val Village: String = "village"

    const val JoiningDate: String = "joining_date"
    const val AssessmentScore: String = "assessment_score"
    const val AdminId: String = "adminId"
}
