package com.nitiaayog.apnesaathi.networkadapter.apiconstants

object ApiConstants {

    const val StatusCode: String = "statusCode"
    const val Message: String = "message"
    const val VolunteerAssignment: String = "volunteerassignment"
    const val LoginOtp: String = "loginOTP"
    const val UserId: String = "user_id"
    const val UserName: String = "user_name"
    const val Block: String = "block"
    const val State: String = "state"
    const val District: String = "district"
    const val PhoneNumber: String = "phoneNo"
    const val Gender: String = "gender"
    const val Age: String = "age"
    const val UserInfo: String = "user_info"
    const val Role: String = "role"

    const val Volunteer: String = "volunteer"
    const val GrievanceTracking: String = "greivanceTrackingList"
    const val FirstName: String = "firstName"
    const val Address: String = "address"
    const val LastId: String = "last_id"
    const val RequestedData: String = "requested_data"
    const val VolunteerId: String = "idvolunteer"
    const val VolunteerNotRegisterErrorMessage: String = "Invalid User"

    const val MedicalGrievances: String = "medicalandgreivance"
    const val CallId: String = "callid"
    const val SrCitizenName: String = "namesrcitizen"
    const val SrCitizenContactNumber: String = "phonenosrcitizen"
    const val SrCitizenAge: String = "agesrcitizen"
    const val SrCitizenGender: String = "gendersrcitizen"
    const val SrCitizenAddress: String = "addresssrcitizen"
    const val SrCitizenEmailId: String = "emailsrcitizen"
    const val SrCitizenState: String = "statesrcitizen"
    const val SrCitizenDistrict: String = "districtsrcitizen"
    const val SrCitizenBlock: String = "blocknamesrcitizen"
    const val SrCitizenCallStatusCode: String = "callstatusCode"
    const val SrCitizenCallStatusSubCode: String = "callstatussubCode"
    const val SrCitizenTalkedWith: String = "talkedwith"
    const val Remark: String = "remarks"
    const val LoggedDateTime: String = "loggeddateTime"

    const val GrievanceId: String = "idgrevance"
    const val GrievanceType: String = "greivanceType"
    const val GrievanceStatus: String = "status"
    const val IsDiabetic: String = "diabetic"
    const val Description: String = "description"
    const val IsBloodPressure: String = "bloodpressure"
    const val LungAilment: String = "lungailment"
    const val CancerOrMajorSurgery: String = "cancer_or_majorsurgery"
    const val OtherAilments: String = "other_ailments"
    const val RemarkOnMedicalHistory: String = "remarks_medical_history"
    const val InfoTalkAbout: String = "related_info_talked_about"

    const val IsSrCitizenAwareOfCovid19: String = "isSrCitizenAwareOfCovid_19"
    const val IsSymptomsPreventionDiscussed: String = "isSymptomsPreventionTaken"
    const val WhichPracticeNotFollowed: String = "practiceNotAllowed"

    const val NoticedBehaviouralChange: String = "behavioural_change_noticed"
    const val HasCovidSymptoms: String = "iscovidsymptoms"
    const val HasCough: String = "hascough"
    const val HasFever: String = "hasfever"
    const val HasShortnessOfBreath: String = "has_shortnes_of_breath"
    const val HasSoreThroat: String = "has_sorethroat"
    const val QuarantineStatus: String = "quarantinestatus"
    const val LackOfEssentialServices: String = "lackofessentialservices"
    const val FoodShortage: String = "foodshortage"
    const val MedicineShortage: String = "medicineshortage"
    const val AccessToBankingIssue: String = "aceesstobankingissue"
    const val UtilityIssue: String = "utilitysupplyissue"
    const val HygieneIssue: String = "hygieneissue"
    const val SafetyIssue: String = "safetyissue"
    const val EmergencyServiceIssue: String = "emergencyserviceissue"
    const val PhoneInternetIssue: String = "phoneandinternetissue"
    const val IsEmergencyServicesRequired: String = "isemergencyservicerequired"
    const val ImpRemarkInfo: String = "remakrsimportantinfo"
    const val CreatedDate: String = "loggeddattime"
    const val GrievanceCreatedDate: String = "createdDate"
    const val Priority: String = "priority"
    const val LastUpdateOn: String = "lastUpdatedOn"
    const val UnderReviewDate: String = "underReviewDate"
    const val ResolvedDate: String = "resolvedDate"
    const val ReviewRemarks: String = "underReviewRemarks"
    const val ResolvedRemarks: String = "resolvedRemarks"
    const val phoneNo: String = "phoneNo"

    const val Profileidvolunteer: String = "idvolunteer"
    const val ProfileFirstName: String = "firstName"
    const val ProfileLstname: String = "lastName"
    const val ProfileAddress: String = "address"
    const val ProfileEmail: String = "email"

    const val GrievanceTrackingId: String = "trackingId"

    const val AdminId: String = "adminId"
    const val Password: String = "password"
}