package com.nitiaayog.apnesaathi.networkadapter.apiconstants

object ApiConstants {

    const val STATUS_EXCEPTION: Int = -1
    const val STATUS_ERROR: Int = 0

    const val StatusCode: String = "statusCode"
    const val UserId: String = "user_id"
    const val UserName: String = "user_name"
    const val Block: String = "block"
    const val State: String = "state"
    const val District: String = "district"
    const val PhoneNumber: String = "phoneNo"
    const val Gender: String = "gender"
    const val Age: String = "age"
    const val UserInfo: String = "user_info"

    const val Volunteer: String = "volunteer"
    const val FirstName: String = "firstName"
    const val Address: String = "address"
    const val VolunteerId: String = "idvolunteer"

    const val AssessmentQuestions: String = "assessment_questions"
    const val QuestionId: String = "q_id"
    const val QuestionData: String = "q_data"
    const val OptionId: String = "option_id"
    const val Option: String = "option"
    const val IsCorrectOption: String = "is_correct_option"
    const val AvailableOptions: String = "available_options"

    const val MedicalGrievances: String = "medicalandgreivance"
    const val CallsList: String = "volunteercallList"
    const val CallId: String = "callid"
    const val SrCitizenName: String = "namesrcitizen"
    const val SrCitizenContactNumber: String = "phonenosrcitizen"
    const val SrCitizenAge: String = "agesrcitizen"
    const val SrCitizenGender: String = "gendersrcitizen"
    const val SrCitizenAddress: String = "addresssrcitizen"
    const val SrCitizenEmailId: String = "emailsrcitizen"
    const val SrCitizenState: String = "statesrcitizen"
    const val SrCitizenDistrict: String = "districtsrcitizen"
    const val SrCitizenBlock: String = "blocknamesrcitizen"
    const val SrCitizenCallStatusCode: String = "callstatusCode"
    const val SrCitizenSubStatusCode: String = "callstatussubCode"
    const val SrCitizenTalkedWith: String = "talkedwith"
    const val Remark: String = "remarks"

    const val GrievanceId: String = "idgrevance"
    const val IsDiabetic: String = "diabetic"
    const val IsBloodPressure: String = "bloodpressure"
    const val LungAilment: String = "lungailment"
    const val CancerOrMajorSurgery: String = "cancer_or_majorsurgery"
    const val OtherAilments: String = "other_ailments"
    const val RemarkOnMedicalHistory: String = "remarks_medical_history"
    const val InfoTalkAbout: String = "related_info_talked_about"
    const val NoticedBehaviouralChange: String = "behavioural_change_noticed"
    const val HasCovidSymptoms: String = "iscovidsymptoms"
    const val HasCough: String = "hascough"
    const val HasFever: String = "hasfever"
    const val HasShortnessOfBreath: String = "has_shortnes_of_breath"
    const val HasSoreThroat: String = "has_sorethroat"
    const val QuarantineStatus: String = "quarantinestatus"
    const val FoodShortage: String = "foodshortage"
    const val MedicineShortage: String = "medicineshortage"
    const val AccessToBankingIssue: String = "aceesstobankingissue"
    const val UtilityIssue: String = "utilitysupplyissue"
    const val HygieneIssue: String = "hygieneissue"
    const val SafetyIssue: String = "safetyissue"
    const val EmergencyServiceIssue: String = "emergencyserviceissue"
    const val PhoneInternetIssue: String = "phoneandinternetissue"
    const val IsEmergencyServicesRequired: String = "isemergencyservicerequired"
    const val ImpRemarkInfo: String = "remakrsimportantinfo"
    const val CreatedDate: String = "loggeddattime"
}